language: node_js

cache:
  directories:
    - ~/.npm
    - node_modules

branches:
  only:
    - master

script:
- yarn build
- yarn ci

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
